[package]
name = "simple-web-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.3.1", features = ["server", "http1"] }
tokio = "1.38.0"
serde = "1.0.203"
